name: Kong Validate

on:
  push:
    paths:
      - 'kong.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install decK
        run: |
          curl -sL https://github.com/kong/deck/releases/latest/download/deck-linux-amd64.tar.gz | tar xz
          sudo mv deck /usr/local/bin/

      - name: Validate configuration
        run: |
          deck validate -s kong.yaml
