name: Kong Diff

on:
  pull_request:
    paths:
      - 'kong.yaml'

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install decK
        run: |
          curl -sL https://github.com/kong/deck/releases/latest/download/deck-linux-amd64.tar.gz | tar xz
          sudo mv deck /usr/local/bin/

      - name: Show diff with Kong Konnect
        run: |
          deck diff -s kong.yaml --konnect-addr ${{ secrets.KONG_ADDR }} --konnect-token ${{ secrets.DECK_KONNECT_TOKEN }}
