name: GitHub Actions Demo
on:
  push:
    branches:
    - 'develop'
    - 'master'
jobs:
  deploy_to_clouds:
    runs-on: ubuntu-latest
    name: Apply the decK configuration
    steps:
      - uses: kong/setup-deck@v1
      #
      # can be used to ensure no changes have occurred outside of our repo
      # - run: deck konnect diff --non-zero-exit-code
      #
      - run: deck gateway sync
