name: Kong Konnect Deploy
on:
  pull_request:
    branches: [ develop, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Make sure checkout your git repository
    - uses: actions/checkout@v2
      name: "checkout"
    # Ping to your Kong instance
    - name: decK ping
      id: decK_ping
      with:
        command: "ping"
        options: "--kong-addr ${{ secrets.KONG_ADDR }} --headers ${{ secrets.KONG_HEADERS }}"  # This option can be ommited.  But if you want to use this you need to set the secrets in your repo settings to make it work
    # Check the structure of your files
    - name: decK validate
      id: decK_validate
      with:
        command: " gateway validate"
        options: "--kong-addr ${{ secrets.KONG_ADDR }} --headers ${{ secrets.KONG_HEADERS }}" 
        kong_workspaces: "default"
        #github_token: ${{ secrets.GITHUB_TOKEN }}
    # Check diff between the files and the Kong instance
    - name: decK diff
      id: decK_diff
      with:
        command: "gateway diff"
        options: "--kong-addr ${{ secrets.KONG_ADDR }} --headers ${{ secrets.KONG_HEADERS }}" 
        kong_workspaces: "default"
        #github_token: ${{ secrets.GITHUB_TOKEN }}
    # Sync the state of the files to the Kong instance and update the deployment status in your repo by GitHub Deployment API
    - name: decK sync
      id: decK_sync
      with:
        command: "gateway sync"
        options: "--kong-addr ${{ secrets.KONG_ADDR }} --headers ${{ secrets.KONG_HEADERS }}" 
        kong_workspaces: "test/kong"
        #github_token: ${{ secrets.GITHUB_TOKEN }}
